services:
  db:
    image: postgres:15-alpine
    container_name: postgres-sql_analyze
    command: postgres -c shared_preload_libraries=pg_stat_statements

    env_file:
      - ../.env

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d sql_analyze"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis-sql_analyze

    command: redis-server --appendonly yes

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

    volumes:
      - redis_data:/data

  api:
    container_name: construtor

    build:
      context: ..
      dockerfile: deployments/Dockerfile

    ports:
      - "3000:8080"

    env_file:
      - ../.env

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  migrate:
    image: migrate/migrate:v4.17.0
    container_name: migrate-sql_analyze
    volumes:
      - ../migrations:/migrations
    env_file:
      - ../.env
    entrypoint: ["sh", "-c"]

    command:
      - >
        migrate -path=/migrations -database "postgres://$$POSTGRES_USER:$$POSTGRES_PASSWORD@db:$$POSTGRES_PORT/$$POSTGRES_DB?sslmode=$$POSTGRES_SSLMODE" up

    depends_on:
      db:
        condition: service_healthy
    restart: "no"

volumes:
  postgres_data:
  redis_data: